# Generated by Django 5.2.17 on 2026-09-28 21:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('customer_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('placed', 'Placed')], default='placed', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_quantity', models.PositiveIntegerField()),
                ('idempotency_key', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id', '-created_at'], name='order_user_created_idx'), models.Index(fields=['status', '-created_at'], name='order_status_created_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('subtotal__gte', 0)), name='order_subtotal_gte_0'), models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('user_id', 'idempotency_key'), name='order_user_idempotency_key_unique')],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_id', models.UUIDField()),
                ('product_name', models.CharField(max_length=200)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.PositiveIntegerField()),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('order', 'product_id'), name='order_item_unique_product'), models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='order_item_quantity_gte_1'), models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='order_item_unit_price_gte_0')],
            },
        ),
    ]
