# Generated by Django 5.2.17 on 2026-09-29 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
